import { Title, Card, Container, Grid, Badge, Center, Image, Stack, Group } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import { fetchAllPokemon } from "../service/pokemon";
import styles from "../styles/Home.module.css";
import { Text } from "@mantine/core";
import { useEffect } from "react";
import useSWR from "swr";
import { Pokemon } from "../interfaces/interfaces";

const COLORS_KEY = {
  GRASS: "green",
  POISON: "grape",
  FIRE: "red",
  WATER: "cyan",
  FLY: "blue",
  NORMAL: "gray",
  BUG: "lime",
  
};

const SingleCard = ({ pokemon }: { pokemon: Pokemon }) => {
  return (
    <Card radius="md" shadow="sm" withBorder key={pokemon.id}>
      <Text align="center" size="md" weight={500} transform="uppercase">
        {pokemon.name}
      </Text>
        <Stack align='center'>
          <Image width={150} height={150} radius="md" src={pokemon.sprites.other?.["official-artwork"].front_default} alt={pokemon.name} />
        <Group>
        {pokemon.types.map((T) => {
          return (
            <Badge key={T.slot} color={COLORS_KEY[T.type.name.toUpperCase() as keyof typeof COLORS_KEY]}>
              {T.type.name}
            </Badge>
          );
        })}
        </Group>
        </Stack>
    </Card>
  );
};

const ListPokemon = ({ pokemonList }: { pokemonList: Pokemon[] }) => {
  return (
    <Grid gutter="md">
      {pokemonList.map((T) => (
        <Grid.Col span={4} key={T.id}>
          <SingleCard pokemon={T} />
        </Grid.Col>
      ))}
    </Grid>
  );
};

const Home: NextPage = () => {
  const { data, error } = useSWR<Pokemon[]>("allPokemons", fetchAllPokemon);
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokéflex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Title order={1}>Pokéflex</Title>
        {!!data && <ListPokemon pokemonList={data} />}
      </Container>
    </div>
  );
};

export default Home;
