import { Text } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import { Suspense } from "react";
import dynamic from "next/dynamic";

const PokemonList = dynamic(
  async () => await await import("../component/PokemonList/PokemonList")
);

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pokéflex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Suspense fallback={<Text>Loading ppage...</Text>}>
        <PokemonList />
      </Suspense>
    </div>
  );
};

export default Home;
