import { Title } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import { fetchAllPokemon } from "../service/pokemon";
import styles from "../styles/Home.module.css";
import { Text } from "@mantine/core";
import { useEffect } from "react";
import useSWR from "swr";
import { Pokemon } from "../interfaces/interfaces";

const usePokemonData = async () => {
  const pokemonList = await fetchAllPokemon();
  return pokemonList;
};

const ListPokemon = () => {};

const Home: NextPage = () => {
  const { data, error } = useSWR<Pokemon[]>("allPokemons", fetchAllPokemon);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title order={1}>Pokéflex</Title>
      {!!data && data.map((T) => <p key={T.id}>{T.name}</p>)}
    </div>
  );
};

export default Home;
